### ISSUE TITLE
add example use case

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/reading-ios-looping-and-conditionals#4]
When we intro if/else conditionals and the concept of flow control, let's give a use case. Why do we need conditional statements? What are they good for? Maybe something like: you're building an app that delivers video content to users. if the user is under 18, they can't view certain content.

I know there is another example after you explain how if/else works but I think good to throw something out there right away to give folks a sense of why this reading is important.

@markedwardmurray

**Comment by markedwardmurray** [comment]
addressed in https://github.com/learn-co-curriculum/reading-ios-looping-and-conditionals/commit/783acb014d86ea71c74ee920f3014cda6c043b2d
