### ISSUE TITLE
Table with `||` shows incorrectly in Learn

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/reading-ios-looping-and-conditionals#7]
https://github.com/learn-co-curriculum/reading-ios-looping-and-conditionals#combining-conditionals

Wrapping the `||` double pipe symbol into a code snippet let's it display correctly on Github, but Learn gets confused. I think it sees the back ticks as the content of the first two cells and cuts off the actual content because there aren't additional columns in the table.

@kvignali @matbalez 

https://learn.co/admin/lessons/7322

**Comment by kvignali** [comment]
thanks for pointing out mark! logging a issue for markdown rendering differently on Learn versus Github on ironboard.

**Comment by markedwardmurray** [comment]
closing this on the repo

**Comment by AnnJohn** [comment]
Closing issue. Handed to engineering.
